from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "src" / "anylist_sdk" / "proto" / "schema.json"
OUTPUT = ROOT / "src" / "anylist_sdk" / "proto" / "__init__.pyi"

SCALARS = {
    "double": "float",
    "float": "float",
    "int64": "int",
    "uint64": "int",
    "int32": "int",
    "fixed64": "int",
    "fixed32": "int",
    "bool": "bool",
    "string": "str",
    "bytes": "bytes",
    "uint32": "int",
    "sfixed32": "int",
    "sfixed64": "int",
    "sint32": "int",
    "sint64": "int",
}


def _field_type(raw: dict[str, Any], messages: set[str], enums: set[str]) -> str:
    raw_type = str(raw["type"])
    value_type = SCALARS.get(raw_type, "int" if raw_type in enums else raw_type)
    rule = raw["rule"]
    if rule == "map":
        key_type = SCALARS.get(str(raw["keytype"]), "int")
        return f"MutableMapping[{key_type}, {value_type}]"
    if rule == "repeated":
        if raw_type in messages:
            return f"_RepeatedComposite[{value_type}]"
        return f"MutableSequence[{value_type}]"
    return value_type


def _constructor_type(raw: dict[str, Any], messages: set[str], enums: set[str]) -> str:
    raw_type = str(raw["type"])
    value_type = SCALARS.get(raw_type, "int" if raw_type in enums else raw_type)
    rule = raw["rule"]
    if rule == "map":
        key_type = SCALARS.get(str(raw["keytype"]), "int")
        return f"Mapping[{key_type}, {value_type}]"
    if rule == "repeated":
        return f"Iterable[{value_type}]"
    return value_type


def generate() -> str:
    schema = json.loads(SCHEMA.read_text("utf-8"))
    messages = {str(m["name"]) for m in schema["messages"]}
    top_enums = {str(e["name"]) for e in schema.get("enums", [])}
    lines = [
        "# Generated by tools/generate_proto_stubs.py from proto/schema.json.",
        "# Do not hand-edit: the embedded official AnyList schema is the source of truth.",
        "from collections.abc import Iterable, Iterator, Mapping, MutableMapping, MutableSequence",
        "from typing import Any, Generic, TypeVar, overload",
        "",
        "from google.protobuf.message import Message",
        "",
        '_T = TypeVar("_T")',
        "",
        "class _EnumWrapper:",
        "    def Name(self, number: int) -> str: ...",
        "    def Value(self, name: str) -> int: ...",
        "    def keys(self) -> list[str]: ...",
        "    def values(self) -> list[int]: ...",
        "    def items(self) -> list[tuple[str, int]]: ...",
        "",
        "class _RepeatedComposite(Generic[_T]):",
        "    def add(self, **kwargs: Any) -> _T: ...",
        "    def __len__(self) -> int: ...",
        "    def __iter__(self) -> Iterator[_T]: ...",
        "    @overload",
        "    def __getitem__(self, index: int) -> _T: ...",
        "    @overload",
        "    def __getitem__(self, index: slice) -> list[_T]: ...",
        "    @overload",
        "    def __setitem__(self, index: int, value: _T) -> None: ...",
        "    @overload",
        "    def __setitem__(self, index: slice, value: Iterable[_T]) -> None: ...",
        "    def __delitem__(self, index: int | slice) -> None: ...",
        "    def insert(self, index: int, value: _T) -> None: ...",
        "    def append(self, value: _T) -> None: ...",
        "    def extend(self, values: Iterable[_T]) -> None: ...",
        "    def remove(self, value: _T) -> None: ...",
        "",
    ]

    for enum in schema.get("enums", []):
        enum_name = str(enum["name"])
        wrapper_name = f"_{enum_name}Wrapper"
        lines.append(f"class {wrapper_name}(_EnumWrapper):")
        for value in enum.get("values", []):
            lines.append(f"    {value['name']}: int")
        if not enum.get("values"):
            lines.append("    pass")
        lines.append(f"{enum_name}: {wrapper_name}")
        lines.append("")

    for message in schema["messages"]:
        name = str(message["name"])
        local_enums = {str(e["name"]) for e in message.get("enums", [])}
        enum_scope = top_enums | local_enums
        lines.append(f"class {name}(Message):")
        if not message.get("fields") and not message.get("enums"):
            lines.append("    pass")
            lines.append("")
            continue

        for enum in message.get("enums", []):
            enum_name = str(enum["name"])
            lines.append(f"    class _{enum_name}Wrapper(_EnumWrapper):")
            for value in enum.get("values", []):
                lines.append(f"        {value['name']}: int")
            if not enum.get("values"):
                lines.append("        pass")
            lines.append(f"    {enum_name}: _{enum_name}Wrapper")
        if message.get("enums") and message.get("fields"):
            lines.append("")

        for field in message.get("fields", []):
            lines.append(f"    {field['name']}: {_field_type(field, messages, enum_scope)}")

        fields = list(message.get("fields", []))
        lines.append("")
        if fields:
            lines.append("    def __init__(self, *,")
            for field in fields:
                field_type = _constructor_type(field, messages, enum_scope)
                lines.append(f"        {field['name']}: {field_type} = ...,")
            lines.append("    ) -> None: ...")
        else:
            lines.append("    def __init__(self) -> None: ...")
        lines.append("")

    lines.extend(
        [
            "class _PBNamespace:",
        ]
    )
    for enum in schema.get("enums", []):
        enum_name = str(enum["name"])
        lines.append(f"    {enum_name}: _{enum_name}Wrapper")
    for message in schema["messages"]:
        name = str(message["name"])
        lines.append(f"    {name}: type[{name}]")
    lines.extend(
        [
            "",
            "PB: _PBNamespace",
            "",
            "def message_class(name: str) -> type[Message]: ...",
            "def new(name: str, **values: Any) -> Message: ...",
            "def assign(msg: _T, field_name: str, value: Any) -> _T: ...",
            "def decode(name: str, payload: bytes) -> Message: ...",
            "def encode(msg: Message) -> bytes: ...",
            "def __getattr__(name: str) -> Any: ...",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate static typing stubs for AnyList's embedded official protobuf schema."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero instead of writing when the committed stub is stale",
    )
    args = parser.parse_args()

    generated = generate()
    if args.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            return 1
        return 0 if current == generated else 1

    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
